Added two new fuctions to dict API
michaelrsweet/pdfio pull request #63
Opened 2024-02-09 15:21 UTC by lgg2

Hello,

I have added two new functions to iterate a dictionary without the use of a callback. I have also include a test purpose file.

Feel free to correct the changes. I think that are usefull.

P.D.: Sorry, I see in the commit that I have include the "test_mod" executable. Delete it.

Thanks.

2024-02-09 18:02 UTC, michaelrsweet requested changes
I'm OK with this in concept, but see my notes.

Also, all APIs need to range check the input arguments - look for NULL pointers, etc.

2024-02-09 18:02 UTC, michaelrsweet commented on pdfio-dict.c
> +pdfioDictGetNumKeys(pdfio_dict_t  *dict) // I - Dictionary
Should be `pdfioDictGetNumPairs`.

2024-02-09 18:02 UTC, michaelrsweet commented on pdfio-dict.c
> +bool								// O - Value
Should return the key string.

2024-02-09 18:02 UTC, michaelrsweet commented on pdfio-dict.c
> + 		key->type = (pdfio_valtype_t **)(dict->pairs[index].value.type);
`dist->pairs[index].value.type` is a literal `pdfio_valtype_t` value, not a pointer or pointer to pointer...

2024-02-09 18:02 UTC, michaelrsweet commented on pdfio.h
> +typedef struct pdfio_dictKey_s
Don't need this.

2024-02-09 18:40 UTC, lgg2 commented on pdfio-dict.c
> +bool								// O - Value
The problem that I see only returning a string with the key It is that also It is of interest get the type with the save call.

2024-02-09 18:45 UTC, lgg2 commented on pdfio-dict.c
> + 		key->type = (pdfio_valtype_t **)(dict->pairs[index].value.type);
It is the way in that I manage to recall the value itself among the key string pointer.

2024-02-09 18:47 UTC, lgg2 commented
I'm not a full time programmer (only for hobby and some times for solve something in the work) and It is also my first "pull request" (also again in a very rudimentary way).

The reason for this two functions It is no need the use of a callback for each time that review for a dictionary keys.

2024-02-10 00:51 UTC, michaelrsweet commented on pdfio-dict.c
> + 		key->type = (pdfio_valtype_t **)(dict->pairs[index].value.type);
That doesn't make any sense. `pdfio_valtype_t` is an enum (integer). You aren't returning the address of the enum, you are casting the enum value to a pointer which isn't valid.

2024-02-10 00:53 UTC, michaelrsweet commented on pdfio-dict.c
> +bool								// O - Value
There is already a function to get the type associated with a key. Alternately you could have a `pdfio_valtype_t *` argument that (optionally) returns the type in the pointed variable. Returning the results via a struct pointer and separately returning a bool doesn't make a lot of sense.

2024-10-25 21:49 UTC, michaelrsweet commented
[master afac835] Add pdfioDictGetKey and pdfioDictGetNumPairs APIs (Issue #63)

2024-10-25 21:49 UTC, closed without merging