Get name from object
michaelrsweet/pdfio pull request #76
Opened 2024-09-25 14:07 UTC by vlasovsoft1979

For example, store Image ColorSpace in the separate object:

```
8 0 obj
<<
/Type /XObject
/Subtype /Image
/ColorSpace 10 0 R
>>
...
10 0 obj
/DeviceRGB
endobj

```

2024-09-25 14:48 UTC, michaelrsweet requested changes
Minor nit on the addition to the header. Also, if we have a getter we should have a way to create a name object (`pdfioFileCreateNameObj`).

2024-09-25 14:48 UTC, michaelrsweet commented on pdfio.h
> +extern const char *pdfioObjGetName(pdfio_obj_t *obj) _PDFIO_PUBLIC;
Tab between "const char" and "*pdfioObjGetName". Also, please move this down between ...GetLength and ...GetNumber so it is sorted alphabetically.

2024-09-27 14:42 UTC, vlasovsoft1979 commented
@michaelrsweet 
This is my first PR to github. Please let me know if I forget something. I've fixed your comments. Now it's your turn.

2024-09-27 17:16 UTC, michaelrsweet commented on pdfio-object.c
> +//
Minor nit, please move this later in the file before pdfioObjGetNumber.

2024-09-27 17:44 UTC, michaelrsweet approved these changes

2024-09-27 17:45 UTC, michaelrsweet commented
OK, holding for the next feature release (have a bug fix release to do first...)

2024-10-25 21:14 UTC, merged