Update in documentation
michaelrsweet/pdfio pull request #78
Opened 2024-10-14 08:07 UTC by uddhavphatak

Basics of PDF File have been added. It mainly includes the following:

- Understanding PDF Files:
  - A small PDF File: an example pdf file
  - Header
  - Body
  - Cross-Reference Table
  - Trailer
  - How a PDF File is Read
  - How a PDF File is Written

2024-10-14 20:19 UTC, michaelrsweet requested changes
A really good start!

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +A PDF file is structure in a way, so that it would be displayed in the same way
Might be better to say something like:

> A PDF file provides data and commands for displaying pages of graphics and text, and is structured in a way that allows it to be displayed in the same way across multiple devices and platforms. The following is a PDF which shows "Hello, World!" on one page:

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +- For Example:
This shouldn't be a bullet list, just another sentence that is part of the paragraph.

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +  - For simplicity, we would assume generation numbers to be always zero and ignore them.
"we will assume"

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +0000000000 65535   **f Special entry**
The "f" and "n" inside the `**` should be right after the generation number.

Also, `**` doesn't work inside code fences; I'd just use a leading `%` since that is also valid PDF syntax.

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +which contains at least the /Size entry (which gives the number of entries in the cross-reference table)
Drop the "which gives the" inside the parens here and on the next line.

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +trailer        **Trailer keyword**
Ditto here for changing `** something **` to `% something`.

2024-10-14 20:19 UTC, michaelrsweet commented on doc/pdfio.md
> +How a PDF File is Read
I don't know that this and the next section are needed since PDFio manages those things for you. Also, there is a lot more involved with reading since there can be multiple trailers/cross-reference tables, encryption, object streams, etc.

2024-10-15 04:12 UTC, uddhavphatak commented on doc/pdfio.md
> +How a PDF File is Read
I added this and the next section for better understanding about the flow of how the computer understands the PDF File.

I did write "This is not an exhaustive description, since there are many possible complications (encryption, linearization, objects, and cross reference streams)." It got mixed into the point 8...

2024-10-15 16:16 UTC, michaelrsweet commented on doc/pdfio.md
> +How a PDF File is Read
OK, better to reword this in relation to the PDFio APIs - pdfioFileOpen does this, pdfioFileCreate does that, etc. Think more "theory of operation" for explaining a complex system or process than a generalization of how all PDF readers/writers do things.

Also, one requirement for PDF reading is that you have access to the entire file (because you skip "randomly" within the file to read different parts) before you can actually read the content. FWIW, there are a few "streaming PDF" variants that can be read incrementally, but since there isn't a reliable way to detect that and they are still valid PDF files, PDFio only reads whole files.

Finally, you are correct that writing can be simpler, and unlike reading it can be streamed vs. just writing a whole file. There are "tricks" for doing streamed writing (mainly using indirect references for stream lengths), and PDFio handles using those as necessary.

2024-10-21 15:09 UTC, uddhavphatak commented
I have decided to remove the "How a PDF File is Read" and  "How a PDF File is Written", because the reading and writing PDF file is explained well in overview. also I am not able to figure out where to put the "understanding PDF Files", for now, I have edited it to be above API Overview. Is it okay for it to be there?

2024-10-21 15:28 UTC, michaelrsweet approved these changes
Yes, I like it.  There are some small whitespace issues I want to fix, but I can handle that after merging. Thanks!

2024-10-25 21:16 UTC, merged